"""Initial migration

Revision ID: 8b6ab0833eb6
Revises: None
Create Date: 2026-06-24 22:00:48.152901

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = '8b6ab0833eb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('processed_emails',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_emails_id'), 'processed_emails', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activation_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_activation_token'), 'users', ['activation_token'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('carriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('competitiveness_score', sa.Float(), nullable=True),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.Column('simulated_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carriers_email'), 'carriers', ['email'], unique=False)
    op.create_index(op.f('ix_carriers_id'), 'carriers', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('default_markup_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('email_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('email_provider', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('smtp_host', sa.String(length=100), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('encrypted_smtp_password', sa.String(length=500), nullable=False),
    sa.Column('imap_host', sa.String(length=100), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('encrypted_imap_password', sa.String(length=500), nullable=False),
    sa.Column('use_dev_mode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_credentials_id'), 'email_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_email_credentials_user_email'), 'email_credentials', ['user_email'], unique=True)
    op.create_index(op.f('ix_email_credentials_user_id'), 'email_credentials', ['user_id'], unique=True)
    op.create_table('freight_quotes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('weight_lbs', sa.Float(), nullable=False),
    sa.Column('dimensions', sa.String(), nullable=True),
    sa.Column('freight_class', sa.String(), nullable=True),
    sa.Column('hazmat', sa.Boolean(), nullable=True),
    sa.Column('accessorials', sa.String(), nullable=True),
    sa.Column('pickup_date', sa.DateTime(), nullable=False),
    sa.Column('first_round_ends_at', sa.DateTime(), nullable=True),
    sa.Column('rebid_round_ends_at', sa.DateTime(), nullable=True),
    sa.Column('quote_expires_at', sa.DateTime(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('markup_percent', sa.Float(), nullable=True),
    sa.Column('margin_amt', sa.Float(), nullable=True),
    sa.Column('margin_pct', sa.Float(), nullable=True),
    sa.Column('winning_carrier_id', sa.Integer(), nullable=True),
    sa.Column('lost_reason', sa.String(), nullable=True),
    sa.Column('competitor_info', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('bol_url', sa.String(), nullable=True),
    sa.Column('invoice_url', sa.String(), nullable=True),
    sa.Column('email_thread_id', sa.String(), nullable=True),
    sa.Column('email_message_id', sa.String(), nullable=True),
    sa.Column('shipment_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winning_carrier_id'], ['carriers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_quotes_id'), 'freight_quotes', ['id'], unique=False)
    op.create_table('carrier_bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freight_quote_id', sa.String(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('bid_amount', sa.Float(), nullable=False),
    sa.Column('transit_time_days', sa.Integer(), nullable=True),
    sa.Column('pickup_window', sa.String(), nullable=True),
    sa.Column('accessorials_text', sa.String(), nullable=True),
    sa.Column('service_level', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('is_winning', sa.Boolean(), nullable=True),
    sa.Column('raw_email', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['freight_quote_id'], ['freight_quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_bids_id'), 'carrier_bids', ['id'], unique=False)
    op.create_table('rfqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freight_quote_id', sa.String(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['freight_quote_id'], ['freight_quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfqs_id'), 'rfqs', ['id'], unique=False)
    op.create_table('state_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freight_quote_id', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=False),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['freight_quote_id'], ['freight_quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_transitions_id'), 'state_transitions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_state_transitions_id'), table_name='state_transitions')
    op.drop_table('state_transitions')
    op.drop_index(op.f('ix_rfqs_id'), table_name='rfqs')
    op.drop_table('rfqs')
    op.drop_index(op.f('ix_carrier_bids_id'), table_name='carrier_bids')
    op.drop_table('carrier_bids')
    op.drop_index(op.f('ix_freight_quotes_id'), table_name='freight_quotes')
    op.drop_table('freight_quotes')
    op.drop_index(op.f('ix_email_credentials_user_id'), table_name='email_credentials')
    op.drop_index(op.f('ix_email_credentials_user_email'), table_name='email_credentials')
    op.drop_index(op.f('ix_email_credentials_id'), table_name='email_credentials')
    op.drop_table('email_credentials')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_carriers_id'), table_name='carriers')
    op.drop_index(op.f('ix_carriers_email'), table_name='carriers')
    op.drop_table('carriers')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_activation_token'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_processed_emails_id'), table_name='processed_emails')
    op.drop_table('processed_emails')
    # ### end Alembic commands ###
